apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/DorAvissar/K8S_Jenkins.git
    targetRevision: main
    path: ConfigFiles
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
