apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: doravissar/k8s_deploy:37
        ports:
        - containerPort: 80
